version: "3"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment: 
      POSTGRES_DB: mosaic_dev 
      POSTGRES_USER: mosaic 
      POSTGRES_PASSWORD: MDaUA2P4ZbkJPCKEM
    ports:
      - "5432:5432"
  api:
    image: node:9.7
    environment: 
        DATABASE_URL: postgres://mosaic:MDaUA2P4ZbkJPCKEM@postgres/mosaic_dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/data
    command: "bash -c 'cd /data/client && yarn install && yarn run build && cd ../server && yarn --production=false && yarn run db:migrate && yarn run start'"
    depends_on:
      - postgres
